### PR TITLE
Support for python3

### PR DESCRIPTION
**Pull request by infamy**
Added support for python 3. While support python2 (not very well tested under2, seems fine)

Changed version to 0.3.0

Support was added without using six, to reduce the decencies required.

### CODE REVIEW

**Comment by jordanh** [comment]
Hey awesome! I'll start looking at this immediately.

**Comment by jordanh** [comment]
Say, @infamy would you mind testing the branch https://github.com/jordanh/neurio-python/tree/0.2.10 on your system?

**Comment by infamy** [comment]
@jordanh the encoding is because of string handling in python3, that was the recommended solution.

I thought I had cleared out that print... oops!

Agree with the 0.2.10, will test and let you know.

**Comment by infamy** [comment]
@jordanh that change, causes a regression,. (to the encode section)

```
  File "/usr/lib/python3.4/base64.py", line 62, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
TypeError: 'str' does not support the buffer interface
```

So 0.2.10 branch does NOT work under python3

**Comment by infamy** [comment]
creds = b64encode(":".join([self.__key,self.__secret])).decode('ascii')

Will not work in python3, as it is MUCH more strict with the str type, hence replacing that with.

try:
      credentials = base64.b64encode(":".join([self.__key,self.__secret]))
    except TypeError:
      credentials = base64.b64encode(self.__key.encode('ascii') + ":".encode('ascii') + self.__secret.encode('ascii')).decode("utf-8")

base64 b54encode, needs a ascii string. (hence the encode). And the whole b54 is actually byte data (thanks python3) so to make it usable in request, you have to go to utf-8. Ugly, but required with the new stricter typing.

**Comment by jordanh** [comment]
Ahh...ok. Time to install Python 3. If possible, I'd like to craft a single statement without needing to rely on an exception pathway.

**Comment by jordanh** [comment]
Ok. I installed python 3, made a few changes, ran the test suite and made a release. Thanks a ton for your assistance!

**Comment by infamy** [comment]
Nice, will take a look at your final solution. Nothing super elegant jumped to mind when I was hacking it to work.

This was more one piece in the puzzle, I have a module for Home-Assitant, done that needed this. So that should be submitted in a few days!

**Pull request merged**
